export const APP_UPDATE_REQUEST = 'APP_UPDATE_REQUEST';
export const APP_UPDATE = 'APP_UPDATE';
export const APP_UPDATE_REJECTED = 'APP_UPDATE_REJECTED';

export const APP_TERMINATE = 'APP_TERMINATE';
export const APP_TERMINATE_REJECTED = 'APP_TERMINATE_REJECTED';
export const APP_TERMINATE_FULFILLED = 'APP_TERMINATE_FULFILLED';

export const APP_START = 'APP_START';
export const APP_START_FULFILLED = 'APP_START_FULFILLED';
export const APP_START_REJECTED = 'APP_START_REJECTED';

export const APP_ERROR = 'APP_ERROR';
