export const OBSERVER_JOIN = 'OBSERVER_JOIN';
export const OBSERVER_JOIN_FULFILLED = 'OBSERVER_JOIN_FULFILLED';
export const OBSERVER_JOIN_REJECTED = 'OBSERVER_JOIN_REJECTED';
export const OBSERVER_KICKED_OUT = 'OBSERVER_KICKED_OUT';
export const OBSERVER_SESSION_INTENT = 'OBSERVER_SESSION_INTENT';
