export const LOBBY_CREATE = 'LOBBY_CREATE';
export const LOBBY_CREATE_FULFILLED = 'LOBBY_CREATE_FULFILLED';
export const LOBBY_CREATE_REJECTED = 'LOBBY_CREATE_REJECTED';

export const LOBBY_JOIN = 'LOBBY_JOIN';
export const LOBBY_JOIN_FULFILLED = 'LOBBY_JOIN_FULFILLED';
export const LOBBY_JOIN_REJECTED = 'LOBBY_JOIN_REJECTED';

export const LOBBY_KICK = 'LOBBY_KICK';
export const LOBBY_KICK_FULFILLED = 'LOBBY_KICK_FULFILLED';
export const LOBBY_KICK_REJECTED = 'LOBBY_KICK_REJECTED';
export const LOBBY_KICKED = 'LOBBY_KICKED';

export const LOBBY_LEAVE = 'LOBBY_LEAVE';
export const LOBBY_LEAVE_FULFILLED = 'LOBBY_LEAVE_FULFILLED';
export const LOBBY_LEAVE_REJECTED = 'LOBBY_LEAVE_REJECTED';

export const LOBBY_LIST = 'LOBBY_LIST';
export const LOBBY_LIST_FULFILLED = 'LOBBY_LIST_FULFILLED';
export const LOBBY_LIST_REJECTED = 'LOBBY_LIST_REJECTED';

export const LOBBY_UPDATE_REQUEST = 'LOBBY_UPDATE_REQUEST';
export const LOBBY_UPDATE_REJECTED = 'LOBBY_UPDATE_REJECTED';
export const LOBBY_UPDATE = 'LOBBY_UPDATE';

